## Chronic Kidney Disease Prediction Model Using Machine Learning

Dataset Description:
--------------------------------
We use the following representation to collect the dataset:-

age - age
bp - blood pressure
sg - specific gravity
al - albumin
su - sugar
rbc - red blood cells
pc - pus cell
pcc - pus cell clumps
ba - bacteria
bgr - blood glucose random
bu - blood urea
sc - serum creatinine
sod - sodium
pot - potassium
hemo - hemoglobin
pcv - packed cell volume
wc - white blood cell count
rc - red blood cell count
htn - hypertension
dm - diabetes mellitus
cad - coronary artery disease
appet - appetite
pe - pedal edema
ane - anemia
class - class (ckd - has chronic kidney disease , notckd - not having chronic kidney disease).

## Importing the Dataset

In [228]:
import pandas as pd
ckd_data = pd.read_csv('kidney_disease.csv')
ckd_data

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44.0,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38.0,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31.0,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32.0,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35.0,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,47.0,6700,4.9,no,no,no,good,no,no,notckd
396,396,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,54.0,7800,6.2,no,no,no,good,no,no,notckd
397,397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,49.0,6600,5.4,no,no,no,good,no,no,notckd
398,398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,51.0,7200,5.9,no,no,no,good,no,no,notckd
399,399,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,53.0,6800,6.1,no,no,no,good,no,no,notckd

In [229]:
ckd_data.isnull().any()

id                False
age                True
bp                 True
sg                 True
al                 True
su                 True
rbc                True
pc                 True
pcc                True
ba                 True
bgr                True
bu                 True
sc                 True
sod                True
pot                True
hemo               True
pcv                True
wc                 True
rc                 True
htn                True
dm                 True
cad                True
appet              True
pe                 True
ane                True
classification    False
dtype: bool

In [230]:
ckd_data.dropna(axis=0, inplace=True)

In [231]:
#Converting the categorial labels into numerical
from sklearn.preprocessing import LabelEncoder
l_en = LabelEncoder()

In [232]:
for i in [6,7,8,9,19,20,21,22,23,24]:
    ckd_data.iloc[:,i] = l_en.fit_transform(ckd_data.iloc[:,i])

In [233]:
ckd_data

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
3,3,48.0,70.0,1.005,4.0,0.0,1,0,1,0,...,32.0,6700,3.9,1,0,0,1,1,1,ckd
9,9,53.0,90.0,1.020,2.0,0.0,0,0,1,0,...,29.0,12100,3.7,1,1,0,1,0,1,ckd
11,11,63.0,70.0,1.010,3.0,0.0,0,0,1,0,...,32.0,4500,3.8,1,1,0,1,1,0,ckd
14,14,68.0,80.0,1.010,3.0,2.0,1,0,1,1,...,16.0,11000,2.6,1,1,1,1,1,0,ckd
20,20,61.0,80.0,1.015,2.0,0.0,0,0,0,0,...,24.0,9200,3.2,1,1,1,1,1,1,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,1,1,0,0,...,47.0,6700,4.9,0,0,0,0,0,0,notckd
396,396,42.0,70.0,1.025,0.0,0.0,1,1,0,0,...,54.0,7800,6.2,0,0,0,0,0,0,notckd
397,397,12.0,80.0,1.020,0.0,0.0,1,1,0,0,...,49.0,6600,5.4,0,0,0,0,0,0,notckd
398,398,17.0,60.0,1.025,0.0,0.0,1,1,0,0,...,51.0,7200,5.9,0,0,0,0,0,0,notckd
399,399,58.0,80.0,1.025,0.0,0.0,1,1,0,0,...,53.0,6800,6.1,0,0,0,0,0,0,notckd

In [234]:
ckd_data.describe()

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,sod,pot,hemo,pcv,htn,dm,cad,appet,pe,ane
count,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,...,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000,158.000000
mean,274.841772,49.563291,74.050633,1.019873,0.797468,0.253165,0.886076,0.816456,0.088608,0.075949,...,138.848101,4.636709,13.687342,41.917722,0.215190,0.177215,0.069620,0.120253,0.126582,0.101266
std,102.998517,15.512244,11.175381,0.005499,1.413130,0.813397,0.318729,0.388343,0.285080,0.265759,...,7.489421,3.476351,2.882204,9.105164,0.412261,0.383065,0.255315,0.326292,0.333562,0.302640
min,3.000000,6.000000,50.000000,1.005000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,111.000000,2.500000,3.100000,9.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,243.000000,39.250000,60.000000,1.020000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,...,135.000000,3.700000,12.600000,37.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,298.500000,50.500000,80.000000,1.020000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,...,139.000000,4.500000,14.250000,44.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,355.750000,60.000000,80.000000,1.025000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,...,144.000000,4.900000,15.775000,48.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,399.000000,83.000000,110.000000,1.025000,4.000000,5.000000,1.000000,1.000000,1.000000,1.000000,...,150.000000,47.000000,17.800000,54.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [235]:
# assigning input, output variables
X = ckd_data.iloc[:,1:25].values
Y = ckd_data['classification'].values
X, Y

(array([[48.0, 70.0, 1.005, ..., 1, 1, 1],
        [53.0, 90.0, 1.02, ..., 1, 0, 1],
        [63.0, 70.0, 1.01, ..., 1, 1, 0],
        ...,
        [12.0, 80.0, 1.02, ..., 0, 0, 0],
        [17.0, 60.0, 1.025, ..., 0, 0, 0],
        [58.0, 80.0, 1.025, ..., 0, 0, 0]], dtype=object),
 array(['ckd', 'ckd', 'ckd', 'ckd', 'ckd', 'ckd', 'ckd', 'ckd', 'ckd',
        'ckd', 'ckd', 'ckd', 'ckd', 'ckd', 'ckd', 'ckd', 'ckd', 'ckd',
        'ckd', 'ckd', 'ckd', 'ckd', 'ckd', 'ckd', 'ckd', 'ckd', 'ckd',
        'ckd', 'ckd', 'ckd', 'ckd', 'ckd', 'ckd', 'ckd', 'ckd', 'ckd',
        'ckd', 'ckd', 'ckd', 'ckd', 'ckd', 'ckd', 'ckd', 'notckd',
        'notckd', 'notckd', 'notckd', 'notckd', 'notckd', 'notckd',
        'notckd', 'notckd', 'notckd', 'notckd', 'notckd', 'notckd',
        'notckd', 'notckd', 'notckd', 'notckd', 'notckd', 'notckd',
        'notckd', 'notckd', 'notckd', 'notckd', 'notckd', 'notckd',
        'notckd', 'notckd', 'notckd', 'notckd', 'notckd', 'notckd',
        'notckd', 'notckd', 'notckd', 'notckd', 'notckd', 'notckd',
        'notckd', 'notckd', 'notckd', 'notckd', 'notckd', 'notckd',
        'notckd', 'notckd', 'notckd', 'notckd', 'notckd', 'notckd',
        'notckd', 'notckd', 'notckd', 'notckd', 'notckd', 'notckd',
        'notckd', 'notckd', 'notckd', 'notckd', 'notckd', 'notckd',
        'notckd', 'notckd', 'notckd', 'notckd', 'notckd', 'notckd',
        'notckd', 'notckd', 'notckd', 'notckd', 'notckd', 'notckd',
        'notckd', 'notckd', 'notckd', 'notckd', 'notckd', 'notckd',
        'notckd', 'notckd', 'notckd', 'notckd', 'notckd', 'notckd',
        'notckd', 'notckd', 'notckd', 'notckd', 'notckd', 'notckd',
        'notckd', 'notckd', 'notckd', 'notckd', 'notckd', 'notckd',
        'notckd', 'notckd', 'notckd', 'notckd', 'notckd', 'notckd',
        'notckd', 'notckd', 'notckd', 'notckd', 'notckd', 'notckd',
        'notckd', 'notckd', 'notckd', 'notckd', 'notckd', 'notckd'],
       dtype=object))

In [236]:
# Splitting the dataset into train, test 
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.30, random_state=0)

In [237]:
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

(110, 24) (48, 24) (110,) (48,)

In [239]:
# Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier
d_tree = DecisionTreeClassifier(criterion='gini')

In [240]:
d_tree.fit(x_train, y_train)

DecisionTreeClassifier()

In [241]:
pred_d_tree = d_tree.predict(x_test)

In [271]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(pred_d_tree, y_test))
print(classification_report(pred_d_tree, y_test))

[[11  0]
 [ 2 35]]
              precision    recall  f1-score   support

         ckd       0.85      1.00      0.92        11
      notckd       1.00      0.95      0.97        37

    accuracy                           0.96        48
   macro avg       0.92      0.97      0.94        48
weighted avg       0.96      0.96      0.96        48

In [272]:
#Logistic Regression
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()

In [274]:
lr.fit(x_train, y_train)

C:\Users\User\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [275]:
lr_pred = lr.predict(x_test)

In [276]:
print(confusion_matrix(lr_pred, y_test))
print(classification_report(lr_pred, y_test))

[[12  0]
 [ 1 35]]
              precision    recall  f1-score   support

         ckd       0.92      1.00      0.96        12
      notckd       1.00      0.97      0.99        36

    accuracy                           0.98        48
   macro avg       0.96      0.99      0.97        48
weighted avg       0.98      0.98      0.98        48

In [277]:
accuracy_score(lr_pred, y_test)

0.9791666666666666

In [247]:
from sklearn.ensemble import GradientBoostingClassifier
gb = GradientBoostingClassifier()

In [248]:
gb.fit(x_train, y_train)

GradientBoostingClassifier()

In [249]:
gb_pred = gb.predict(x_test)

In [250]:
print(confusion_matrix(gb_pred, y_test))
print(classification_report(gb_pred, y_test))

[[12  0]
 [ 1 35]]
              precision    recall  f1-score   support

         ckd       0.92      1.00      0.96        12
      notckd       1.00      0.97      0.99        36

    accuracy                           0.98        48
   macro avg       0.96      0.99      0.97        48
weighted avg       0.98      0.98      0.98        48

In [278]:
accuracy_score(gb_pred, y_test)

0.9791666666666666

In [251]:
#K-nn
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()

In [252]:
knn.fit(x_train, y_train)

KNeighborsClassifier()

In [253]:
knn_pred = knn.predict(x_test)

In [254]:
print(confusion_matrix(knn_pred, y_test))
print(classification_report(knn_pred, y_test))

[[ 7  1]
 [ 6 34]]
              precision    recall  f1-score   support

         ckd       0.54      0.88      0.67         8
      notckd       0.97      0.85      0.91        40

    accuracy                           0.85        48
   macro avg       0.75      0.86      0.79        48
weighted avg       0.90      0.85      0.87        48

In [266]:
#AdaBoost
from sklearn.ensemble import AdaBoostClassifier
adb = AdaBoostClassifier()

In [267]:
adb.fit(x_train, y_train)

AdaBoostClassifier()

In [268]:
adb_pred = adb.predict(x_test)

In [269]:
print(confusion_matrix(adb_pred, y_test))
print(classification_report(adb_pred, y_test))

[[12  0]
 [ 1 35]]
              precision    recall  f1-score   support

         ckd       0.92      1.00      0.96        12
      notckd       1.00      0.97      0.99        36

    accuracy                           0.98        48
   macro avg       0.96      0.99      0.97        48
weighted avg       0.98      0.98      0.98        48

In [280]:
accuracy_score(adb_pred, y_test)

0.9791666666666666